### ISSUE TITLE
Won't request production cert after test cert

### ISSUE THREAD

**Issue by tvdhout** [ddos-clearing-house/ddosdb#11]
When first requesting a _test_ certificate using [letsencrypt.sh](https://github.com/ddos-clearing-house/ddosdb/blob/master/docker/letsencrypt.sh), and after success request a _production_ certificate, the production certificate won't be requested.

I suspect because certbot sees the test certificate, which is still valid, so won't request a new one. After removing the container and corresponding volumes, restarting it and immediately requesting a _production_ certificate, I do successfully get one. 

p.s ddosdb.eu is back online (with IP whitelist)

**Comment by poorting** [comment]
Indeed this was caused by not renewing when an existing certificate already present (even if just a staging certificate). Production request now has '--force-renewal' option so that an existing certificate is always replaced.
