### ISSUE TITLE
Update MISP interaction

### ISSUE THREAD

**Issue by tvdhout** [ddos-clearing-house/ddosdb#18]
the "new" [fingerprint format](https://github.com/ddos-clearing-house/ddos_dissector/blob/main/fingerprint_format.md) breaks the MISP object creation in DDoSDB. 

Lorenzo has made a ["new" version](https://github.com/ddos-clearing-house/converters/blob/master/modules/misp_exporter.py) of the MISP exporter which can form the basis for this. 

We should also add the option to add a sharing group to which to upload the fingerprints when defining the MISP instance on the admin panel.

**Comment by poorting** [comment]
It is not the format that breaks it but the combination with an older pymisp version. Upped the requirements.txt to 2.4.159, which seems to fix it.

**Comment by poorting** [comment]
Sharing group can now also be defined in the admin panel (or left empty for default 'Community').
