### ISSUE TITLE
Creating MISP Tag responded with status code 405

### ISSUE THREAD

**Issue by tvdhout** [ddos-clearing-house/ddosdb#20]
In the MISP push task, creating a MISP tag fails (on a clean install). Traceback:

```
ddosdb_celery_worker | [2022-07-26 13:22:39,583: INFO/MainProcess] Task ddosdb.tasks.misp_push_sync[142c54d1-832e-428f-95fd-2e801864757b] received
ddosdb_celery_worker | [2022-07-26 13:22:39,623: INFO/ForkPoolWorker-1] <QuerySet [<MISP: CONCORDIA MISP>]>
ddosdb_celery_worker | [2022-07-26 13:22:39,649: INFO/ForkPoolWorker-1] filter={'shareable': True}, fields={'_id': 0}
ddosdb_celery_worker | [2022-07-26 13:22:39,729: INFO/ForkPoolWorker-1] Fingerprints to sync: ['49d04991f4a1f2c459406c7f10449fd7']
ddosdb_celery_worker | [2022-07-26 13:22:39,741: INFO/ForkPoolWorker-1] MISP instance: https://misp.concordia-h2020.eu
ddosdb_celery_worker | [2022-07-26 13:22:40,182: INFO/ForkPoolWorker-1] The version of PyMISP recommended by the MISP instance (response['version']) is older than the one you're using now (2.4.159). If you have a problem, please upgrade the MISP instance or use an older PyMISP version.
ddosdb_celery_worker | [2022-07-26 13:22:40,596: INFO/ForkPoolWorker-1] Contacting remote MISP: CONCORDIA MISP @ https://misp.concordia-h2020.eu
ddosdb_celery_worker | [2022-07-26 13:22:40,887: INFO/ForkPoolWorker-1] MISP CONCORDIA MISP knows these fingerprints: []
ddosdb_celery_worker | [2022-07-26 13:22:40,889: INFO/ForkPoolWorker-1] MISP CONCORDIA MISP needs sync for 1 fingerprints ['49d04991f4a1f2c459406c7f10449fd7']
ddosdb_celery_worker | [2022-07-26 13:22:40,889: INFO/ForkPoolWorker-1] Uploading the fingerprint to MISP
ddosdb_celery_worker | [2022-07-26 13:22:41,131: CRITICAL/ForkPoolWorker-1] Creating MISP Tag responded with status code:405
ddosdb_celery_worker | [2022-07-26 13:22:44,209: ERROR/ForkPoolWorker-1] 'NoneType' object is not subscriptable
ddosdb_celery_worker | [2022-07-26 13:22:44,231: INFO/ForkPoolWorker-1] Task ddosdb.tasks.misp_push_sync[142c54d1-832e-428f-95fd-2e801864757b] succeeded in 4.620897262939252s: [{'name': 'CONCORDIA MISP', 'type': 'push', 'status': 555, 'status_reason': 'Connection failed', 'unk_fps': [], 'unk_fps_nr': 0}]
```

**Comment by tvdhout** [comment]
Somehow it did still upload the fingerprint through...

**Comment by tvdhout** [comment]
It uploads the fingerprint without adding the DDoSCH tag. This is also what results in duplicate fingerprints being uploaded, because it looks for existing fingerprints with the DDoSCH tag. Perhaps my account, and therefor authentication token, is not authorized to create new tags. I cannot find this in the MISP GUI. Will investigate further

**Comment by poorting** [comment]
Figured as much. It will now try to create the tags, but if that fails simply add the tag as text instead.
It is possible to do that anyway, but creating a tag explicitly let's you choose a nice colour :-D 

Moved the name & colour of the tag to the top of the Class definition (could be made configurable). The search for existing fingerprints takes it from there as well (instead of hard-coded).
Changed the name to 'DDoS Clearing House'  rather than DDoSCH (which is less meaningful to most people).

If you can confirm this works for you as well we can close this issue.

**Comment by tvdhout** [comment]
It didn't quite work still, because you added the tag to the event after it was uploaded, which again my account was unauthorized :-(

I fixed it by first looking if the tag exists, if not, try to add it, if after that we have a tag, add it just with event.add_tag(name=...) like you did with the 'validated' tag. This works fine.

**Comment by tvdhout** [comment]
I also changed the tag name back to DDoSCH for now, because Marco added that tag to the CONCORDIA MISP for me. We can change this later.
