### ISSUE TITLE
IP's involved - Overview Page

### ISSUE THREAD

**Issue by joaoceron** [ddos-clearing-house/ddosdb#3]
The column "IP's involved" read the field "amplifiers_size" from fingerprint. We should specify a generic field since "amplifiers" is not always present. We might have either amplifiers or attackers.

**Comment by poorting** [comment]
'Either or' or 'and/or'? (that is: is it always one or the other or can it be both in the same fingerprint?)
I can add 'amplifiers_size' and 'attackers_size' (either or both can be zero) at upload time and then also define something like 'IPs_involved' as being the sum of both, and use that for the overview?

**Comment by joaoceron** [comment]
In some cases (rare) we can have both fields. I liked your proposal. we can
check the existence of both fields and sum them.


Best,
João Ceron
