### ISSUE TITLE
Cannot request access on website

### ISSUE THREAD

**Issue by payam-int** [ddos-clearing-house/ddosdb#33]
Hello guys,

I'm trying to request access to ddosdb but in the form I get error from reCAPTCHA. The error is 
```
ERROR for site owner: Invalid site key
```

I would be grateful if you fix this error.

**Comment by poorting** [comment]
DDoSDB itself has no functionality to 'request access', so I'm a bit unsure what issue you are trying to report. Can you provide some more context?
