### ISSUE TITLE
Overview page - IP's involved

### ISSUE THREAD

**Issue by joaoceron** [ddos-clearing-house/ddosdb#4]
The field IP's involved is presented as a float. I would recommend to convert it to int.

**Comment by poorting** [comment]
Any older uploaded fingerprints in the database? They probably show as 'nan' or 'None' in the overview? Re-uploading those (or emptying the database and starting again) should fix it and show IP's involved as an int.

**Comment by joaoceron** [comment]
Yes, there was a previous version. However, when I upload the fingerprint the previous version is overwritten and the filed "IP's involved" keeps showing me as 'float'.

**Comment by poorting** [comment]
Hmm, strange. Can you maybe run this command (on the computer that ddosdb/elasticsearch is running) and mail me the output?
 curl "http://localhost:9200/ddosdb/_search?pretty&_source=key,start_time,duration_sec,ips_involved,avg_bps,avg_pps,total_dst_ports,submit_timestamp,submitter,comment"

**Comment by joaoceron** [comment]
Indeed. I'm attaching the screenshot. It seems that is a visualization problem. 
https://snipboard.io/gVQ0qk.jpg
https://snipboard.io/iA46el.jpg

**Comment by poorting** [comment]
Default seems to show ints on my screen, but it did lack some formatting anyway; so I made it explicit in the overview.html template. Should be solved now. Open a new issue if something similar pops up or it doesn't work
