### ISSUE TITLE
Increase fingerprint upload size

### ISSUE THREAD

**Issue by tvdhout** [ddos-clearing-house/ddosdb#40]
Now we don't send PCAPs, we could allow larger fingerprint sizes to accommodate more source IP addresses. 

At the same time we should implement a catch in the dissector to discard obviously spoofed IP addresses from the source (for example in TCP SYN attacks, not for reflection attack vectors). I have an example fingerprint with 6M+ source addresses that is almost 200MB...

**Comment by poorting** [comment]
Fixed by increasing nginx client_max_body_size to 256M
https://github.com/ddos-clearing-house/ddosdb/commit/ae086b02928227ddb4e85260adb6cbc0d385778b
