### ISSUE TITLE
auto-update not working

### ISSUE THREAD

**Issue by joaoceron** [ddos-clearing-house/ddosdb#5]
Auto-update seems not to be working (exception not handled) for DdosDB on DDoSdb-in-a-Box.

/home/ddosdb/.ddosdb/ddosdb/housekeeping/
./check4update.sh

django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.

**Comment by poorting** [comment]
Sent a direct message since I don't want some of the bits of the probable solution to end up here.
