### ISSUE TITLE
ddosdb.org down?

### ISSUE THREAD

**Issue by Wqrld** [ddos-clearing-house/ddosdb#6]
I've seen that the ddosdb.org website has been down for a while. I think this is a very useful project so i was wondering if the existing datasets are stored anywhere else? I can selfhost the system on my own machine but it would help if the original ddosdb data was available.

**Comment by poorting** [comment]
Do you mean the sample set? That is included with the [ddos_dissector](https://github.com/ddos-clearing-house/ddos_dissector). 
The easiest way to run it locally is to use the ['ddosdb-in-a-box'](https://github.com/ddos-clearing-house/dddosdb-in-a-box).

**Comment by Wqrld** [comment]
I was mainly talking about the original ddosdb dataset of processed attacks. I have my own raw pcaps but if i understand correctly the original already had a large amount of processed jsons.

**Comment by Gabitzuu** [comment]
Any news about the website?

**Comment by poorting** [comment]
> Any news about the website?

The ddosdb.org website will not return if that is your question. This project (ddos-clearing-house) is for exchanging information about ddos attacks between collaborating organisations. You  can read more about that here: https://www.nomoreddos.org/en/

**Comment by Wqrld** [comment]
> Any news about the website?

I have setup a small repository of anonymized ddos packet captures here: https://github.com/StopDDoS/packet-captures
If there is any interest in a low barrier-to-entry ddosdb server then i'd be happy to host one. But it would be nice to have some other contributors too.
